plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.plugin.compose'
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.example.carsetting.shared'
    compileSdk 37

    defaultConfig {
        minSdk 34
        targetSdk 37

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        compose true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
        }
    }
}

dependencies {
    implementation libs.androidx.media
    implementation libs.androidx.appcompat
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.graphics
    implementation libs.androidx.compose.ui.tooling
    implementation libs.androidx.compose.material3
    implementation libs.androidx.compose.activity
    implementation libs.androidx.compose.material.icons.extended
    implementation libs.core.ktx
}
